  ("Tortor LLP"),
  ("Euismod Ac Institute"),
  ("Eu Associates"),
  ("Porttitor Consulting"),
  ("Pellentesque Sed Institute"),
  ("Ultrices Limited"),
  ("Enim Mauris Corporation"),
  ("Laoreet Foundation"),
  ("Neque Institute"),
  ("Sagittis Placerat Cras Institute"),
  ("Cum Sociis Institute"),
  ("Urna Nec Incorporated"),
  ("Adipiscing Inc.","ADIP"),
  ("Laoreet Posuere Corp.","LAPOC"),
  ("Donec Dignissim Limited","DODIL"),
  ("Ut Ltd","UTLTD"),
  ("Phasellus Ornare Fusce Ltd","POFL"),
  ("Ac Feugiat Non Incorporated","ACFNI"),
  ("Risus Ltd","RIS"),
  ("Ornare In Faucibus Foundation","OINFF"),
  ("Duis A Mi Company","DUAMI"),
  ("Arcu Aliquam Ultrices Incorporated","AAUI"),
  ("Venenatis Lacus Etiam PC","VLEPC"),
  ("Dictum Eleifend Nunc LLP","DIEN"),
  ("Aenean Euismod Mauris LLP","AEM"),
  ("Egestas Rhoncus Industries","ERI"),
  ("Nam Corporation","NAMCO"),
  ("Molestie Sodales Corp.","MOSCO"),
  ("Et Industries","ETIN"),
  ("Luctus Et Inc.","LUCET"),
  ("Diam At Industries","DIAI"),
  ("Erat Associates","ERATA"),
  ("Adipiscing Fringilla Limited","AFL"),
  ("Quisque Company","QUCO"),
  ("Tincidunt Pede PC","TIPE"),
  ("Euismod Et Foundation","EEF"),
  ("Dui Suspendisse Inc.","DUIS"),
  ("Orci Luctus Et LLC","ORLU"),
  ("Urna Justo Ltd","UJU"),
  ("Nec Eleifend Inc.",NEI");
